### ISSUE TITLE
How to get the added labels ?

### ISSUE THREAD

**Issue by Daniel-W1** [mhmodo10/react-img-annotation#6]
Hey there, thank you so much for this package, it's helping me a lot. I have one question how can I get the labels after they are added when editing, I can see they are logged, but can't seem to know how to get them. 

Thanks.

**Comment by mhmodo10** [comment]
Hello,
Thank you!
If you are using the latest version then you can pass a
'onFieldSelectChange' prop to AnnotationsEditor which is a function that
accepts an object that contains the selected option (label) and the id of
the box it's associated with.
you can use this data to keep track of these changes in your application.

Let me know if you have any questions or features you want me to implement
in the future
Good luck!

**Comment by Daniel-W1** [comment]
Thanks again for the quick and helpful answer. This is a very good, and simplistic annotator. I am sure many people will find it useful. Questions I have are

1. is there a way to see the labels in the edit view? they seem to disappear when I switch to edit mode. 
2. is there a way to customize the color of the menu, and delete icons, or a trick to add background color? sometimes when the image is white they are hard to see.
3. the dropdown isn't immediately visible? I have to click the search input again to see the dropdown. I thought I was supposed to search, but even though the search functionality works, I am not able to see the dropdown lists.

Maybe one feature/idk :) suggestion is to add a small doc, maybe on the npm page, just to show all the possible props and how to use them and avoid ppl coming here and asking easy questions :).

Thanks!

**Comment by mhmodo10** [comment]
Great feedback, those features are currently not available.
As for the visibility of the dropdown menu, this choice was intentional
because when I made it I only wanted to see the options when I clicked on
the search bar in the menu.
I will probably have some time this weekend to work on them.
so if understood correctly these are the features that you would like to
see:
- label positioning control
- menu style customization
- more documentation

Have a great day!

**Comment by mhmodo10** [comment]
Hello,
Sorry for the late reply, but I did not have much time.
I just launched a new version with the requested changes and updated the
readme to include the new changes.

lmk if you have any questions,
good luck!

**Comment by Daniel-W1** [comment]
Hey,

No worries.
Thank you so much, you are amazing. :)

Okay, I will let you know.

**Comment by mhmodo10** [comment]
Closing as it's inactive
