### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Daniel-W1** [mhmodo10/react-img-annotation#8]
Hello @mhmodo10 It's me again. I hope you are doing well.

I wanted to ask about these features in the current package, 

- The rectangle of the defect could be wider.
- The inside (or filling) of the rectangle (bounding box) is colored with transparent color.
- The defect type is shown during the defect modification mode(annotation editor), now it disappears when shifting to the editor from the viewer, it only appears when the user selects a new defect.
- The defect is selected when clicked anywhere on the rectangle( not only the borders).
- logs are removed ( I think there are some logs from the package code)

I was wondering if you can add these features, or tell me if there is a way to have them rn.

Thank you again!

**Comment by mhmodo10** [comment]
Hello
I am not sure what you mean by defect, can you elaborate a bit more?
Also you can style the box however you want using defaultAnnotationStyle on the AnnotationsEditor component.
AnnotationsViewer does not support style changes.
as for logs, most of them are removed, there are still some console logs remaining that will be removed soon.

It would be great if you can attach some images/videos of the issues that you're facing

**Comment by Daniel-W1** [comment]
Hi,

Defect means the bounding box, I used defect because we are showing identified defects in buildings for our project. Sorry if I confused you.

is it possible to show the labels during editing (annotation editor)?

![image](https://github.com/mhmodo10/react-img-annotation/assets/82764803/2b0d1610-8036-4ad5-9f82-bd7b061aae15)
![image](https://github.com/mhmodo10/react-img-annotation/assets/82764803/613d9da9-0371-45c7-91ca-3ad57ca3624e)

the label at the top disappears when showing a labeled bounding box in the editor view.

Thanks

**Comment by mhmodo10** [comment]
Hello
I haven't got to work on this project lately
I will soon be pushing an update to allow you to see the labels.

**Comment by mhmodo10** [comment]
I was not able to reproduce your issue, the labels are showing even during editing
![image](https://github.com/mhmodo10/react-img-annotation/assets/45037687/b2877e2e-82d4-4191-80c2-8fadacdd161e)

perhaps try to update the version of your package to the latest.

**Comment by Daniel-W1** [comment]
it works for newly created annotations, but when you pass bounding boxes through the annotations props, those bounding boxes don't have labels during editing.

```
<AnnotationsEditor
        onFieldSelectChange={(labels) => {}}
        onChange={}
        onDeleteAnnotation={}
        onAddAnnotation={}
        options={}
        annotations={rectangles}       // like this
        image={}
        width={width}
        height={height}
 />
```

**Comment by mhmodo10** [comment]
for add initial selected fields, you should make use of the boxFields prop it should be an array with the following structure
```js
{ boxId: <your_box_id>, fieldIds: [{label: <your_label>, value: <your_value>, key: <your_key>}]}
```

this should work and show the correct fields on init.
